### ISSUE TITLE
Window fullscreen when previous settings aren't found

### ISSUE THREAD

**Issue by voidpirate** [netromdk/dispar#24]
Currently if dispar is launched for the first time (without any previous settings) it will be launched at the user's maximum screen resolution. Might be better to calculate a desirable viewing resolution given the user's current viewing resolution and resize dispar to that instead of fullscreen.

**Comment by netromdk** [comment]
And also change the log message when a settings file isn't found so it doesn't look like an error message. Instead output something like:
> No settings file found at "~/.dispar". Using defaults.

**Comment by voidpirate** [comment]
> And also change the log message when a settings file isn't found so it doesn't look like an error message. Instead output something like:

Great, I won't bug that as a different issue then.

**Comment by voidpirate** [comment]
I will change the log message in #25 since it is related to the settings file anyways

**Comment by netromdk** [comment]
I'll make a self-contained fix for this issue.
