### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [netromdk/dispar#9]
this looks like a nice tool, but will you have a longer README with more details?

keep it up, cheers!

**Comment by netromdk** [comment]
Thanks! Yeah, I haven't gotten around to making a README yet, which is kind of embarrassing haha.. But I'll definitely do that.

And thanks for creating the Capstone project!

**Comment by netromdk** [comment]
It has been done, @aquynh ;)

**Comment by aquynh** [comment]
great, added your project to our website at http://www.capstone-engine.org/showcase.html

cheers!

**Comment by netromdk** [comment]
Thanks, @aquynh!
